<a href="https://colab.research.google.com/github/Omkar210/Statistics-and-ML/blob/main/Day15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
# import warnings
# warnings.filterwarnings("ignore")
# pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest
from scipy.stats import chisquare
from scipy.stats import chi2_contingency
from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson
from statsmodels.stats.rates import test_poisson_2indep
from scipy.stats import chi2
from scipy.stats import f
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
import os
# print(os.getcwd())
# os.chdir('/content/drive/MyDrive/CDAC')
# os.getcwd()

/content/drive/MyDrive/CDAC

'/content/drive/MyDrive/CDAC'

# Case 1
Single predictor single response countinous  

Graph used:
scatter plot

tools:
correction coeffienct

null hypo:
predictor doesn't influence response (only for linear relationship)
if non-linear relation then used some graph for pattern


simple linear regression

# Case 2
multiple regression:

Multiple predictor all continuous, multiple response all continuous

Graph : multiple scatter plot

tools : correletion coeffienct

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='stackloss')
df.head()

   AirFlow  WaterTemp  AcidConc  StackLoss
0       80         27        89         42
1       80         27        88         37
2       75         25        90         37
3       62         24        87         28
4       62         22        87         18

In [ ]:
# Split for train-test
x_train, x_test, y_train, y_test = train_test_split(df.drop('StackLoss', axis=1),df.StackLoss, test_size=0.1, random_state=20)

model = LinearRegression()

model.fit(x_train,y_train)

model.intercept_
model.coef_
model.feature_names_in_
model.score(x_train,y_train)
model.predict(x_test)

array([10.83134469, 14.08460126, 10.34327252])

# Feature Scaling

Techniques:
- Standardization:  original value - mean / sd, Profit: put the values around 0.

- Standardization formula:  x - μ ÷ σ

- Min-Max Scaler: (x - min(col)) / (max(col) - min(value))

- Robust Scaler : (x - median(col)) / (percentile(col,75) - percentile(col,25))

standardize columns

It uses the population sd rather than sample sd which will be little fluctuation

MinMaxScaler

If there is outlier then it may differ

In [ ]:
scl = StandardScaler()

x_train = scl.fit_transform(x_train)
x_test = scl.transform(x_test)

model = LinearRegression()

model.fit(x_train,y_train)

model.intercept_
model.coef_

array([ 6.19332814,  4.40861726, -0.90286981])

when the values are standardize the mean=0 and sd=1 but value in the histogram will not change, only changes the values will follow same propertion.

In [ ]:
scl = StandardScaler()

x_train, x_test, y_train, y_test = train_test_split(df.drop('StackLoss', axis=1),df.StackLoss, test_size=0.1, random_state=20)

x_train = scl.fit_transform(x_train)
x_test = scl.transform(x_test)

x_train = pd.DataFrame(x_train,columns=['AirFlow','WaterTemp','AcidConc'])
x_test = pd.DataFrame(x_test,columns=['AirFlow','WaterTemp','AcidConc'])

model = LinearRegression()
model.fit(x_train,y_train)

model.intercept_   # intercept
model.coef_    # coefficients
model.feature_names_in_

array(['AirFlow', 'WaterTemp', 'AcidConc'], dtype=object)

In [ ]:
df = pd.DataFrame({'Values':[3,6,5,1,6,8,3,8,9,4]})

df['StdScale'] = (df.Values-np.mean(df.Values))/np.std(df.Values,ddof=1)

df['MinMaxScale'] = (df.Values-np.min(df.Values))/(np.max(df.Values)-np.min(df.Values))

df['RobustScale'] = (df.Values-np.median(df.Values))/(np.percentile(df.Values,75)-np.percentile(df.Values,25))

df

   Values  StdScale  MinMaxScale  RobustScale
0       3 -0.890045        0.250    -0.588235
1       6  0.270883        0.625     0.117647
2       5 -0.116093        0.500    -0.117647
3       1 -1.663997        0.000    -1.058824
4       6  0.270883        0.625     0.117647
5       8  1.044835        0.875     0.588235
6       3 -0.890045        0.250    -0.588235
7       8  1.044835        0.875     0.588235
8       9  1.431811        1.000     0.823529
9       4 -0.503069        0.375    -0.352941

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler

robs = RobustScaler()
min_max = MinMaxScaler()
std = StandardScaler()

df['stdScale_sklearn'] = std.fit_transform(df[['Values']])
df['minMaxScale_sklearn'] = min_max.fit_transform(df[['Values']])
df['robustScale_sklearn'] = robs.fit_transform(df[['Values']])

df

,Values,StdScale,MinMaxScale,RobustScale,stdScale_sklearn,minMaxScale_sklearn,robustScale_sklearn
0,3,-0.890045,0.250,-0.588235,-0.938190,0.250,-0.588235
1,6,0.270883,0.625,0.117647,0.285536,0.625,0.117647
2,5,-0.116093,0.500,-0.117647,-0.122373,0.500,-0.117647
3,1,-1.663997,0.000,-1.058824,-1.754007,0.000,-1.058824
4,6,0.270883,0.625,0.117647,0.285536,0.625,0.117647
5,8,1.044835,0.875,0.588235,1.101353,0.875,0.588235
6,3,-0.890045,0.250,-0.588235,-0.938190,0.250,-0.588235
7,8,1.044835,0.875,0.588235,1.101353,0.875,0.588235
8,9,1.431811,1.000,0.823529,1.509261,1.000,0.823529
9,4,-0.503069,0.375,-0.352941,-0.530281,0.375,-0.352941

# Case 3

### **Categorical Regression:**
Response continuous, predictors atleast one categorical and other can be continuous.

* Response Continuous, Predictors will be categorical and continuous.

One Hot Encode:

smaller alphabet will become the reference event.

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name = 'salaries')

df = df[['yrs_service','gender','salary']]

gender_dum = pd.get_dummies(df.gender,drop_first=True).astype(int)

df = pd.concat([df,gender_dum], axis=1)

df = df.drop('gender', axis=1)


# Split for train-test
x_train, x_test, y_train, y_test = train_test_split(df.drop('salary', axis=1),df.salary, test_size=0.2, random_state=20)

# Add constant term
x_train = sm.add_constant(x_train, prepend=False)
x_test = sm.add_constant(x_test, prepend=False)

# Prepare the model
mod1 = sm.OLS(y_train,x_train).fit()

print(mod1.summary())


# Ho yrs_service = 0
# pvalue = 0 reject
# reference value will never appeare in OLS summary
#
# Ho : with respect to female, male does not influence salary
# Ho : With respect to female(reference event), if male is selected then it soes not influence the salary

# With respect to female, if same numbers of experience increase then male's salary decreased by 6000.

                            OLS Regression Results
==============================================================================
Dep. Variable:                 salary   R-squared:                       0.121
Model:                            OLS   Adj. R-squared:                  0.115
Method:                 Least Squares   F-statistic:                     21.52
Date:                Thu, 04 Jun 2026   Prob (F-statistic):           1.75e-09
Time:                        06:37:18   Log-Likelihood:                -3698.4
No. Observations:                 317   AIC:                             7403.
Df Residuals:                     314   BIC:                             7414.
Df Model:                           2
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
yrs_service   701.6382    125.946      5.571      0.000     453.834     949.442
Male         1.368e+04   5434.664      2.517      0.012    2985.362    2.44e+04
const        8.857e+04   5285.500     16.757      0.000    7.82e+04     9.9e+04
==============================================================================
Omnibus:                       28.103   Durbin-Watson:                   1.940
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               34.160
Skew:                           0.696   Prob(JB):                     3.82e-08
Kurtosis:                       3.804   Cond. No.                         99.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Conclusion

- for the row of const: c = 0
- pvalue = 0
- since the pvalue is 0 we REJECT the Ho, that means const term infuences salary
- const = 88570 indicates the salary of person for whom yrs_service = 0 and male = 0 which means gender is female(reference level), the starting salary for males = 88570+13680