<a href="https://colab.research.google.com/github/Omkar210/Statistics-and-ML/blob/main/Day11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
# import warnings
# warnings.filterwarnings("ignore")
# pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest
from scipy.stats import chisquare
from scipy.stats import chi2_contingency
import os
# print(os.getcwd())
# os.chdir('/content/drive/MyDrive/CDAC')
# os.getcwd()

### Paired t-Test

This test is used when we have two paired samples, Avg difference between the paired values is compared against the claim value to established whether the difference is statistically signaficant or not.

**Key Word:** before, after

- sample size has to be same

In [ ]:
before = np.array([12,14,10,9,8,13])
after = np.array([11.8,9.7,11.3,8.2,7.2,12.3])

# before - after
# bcuz before is greater values after values come down

# Ho avg(before - after) >= 2
# Ha avg(before - after) < 2  ===>  Left Tail Test

d = before - after
np.mean(d)

ssw.ttost_paired(before,after,low=2,upp=2)

(np.float64(0.8954696830206994),
 (np.float64(-1.4413160909218492),
  np.float64(0.8954696830206994),
  np.float64(5.0)),
 (np.float64(-1.4413160909218492),
  np.float64(0.10453031697930062),
  np.float64(5.0)))

In [ ]:
scipy.stats.ttest_1samp(before - after,popmean=2,alternative='less')

TtestResult(statistic=np.float64(-1.4413160909218492), pvalue=np.float64(0.10453031697930062), df=np.int64(5))

Mathematics

In [ ]:
(np.mean(d) -2)/((np.std(d,ddof=1))/6**0.5)

np.float64(-1.4413160909218492)

In [ ]:
t.cdf(-1.4413160909218492,5)

np.float64(0.10453031697930062)

## one way ANOVA (ANalysis Of VAriance)

Purpose:
- This test is used when we have multiple sample (more than 2)
- This test will check all the pair of mean and compare whether they can be considered as equal or not

Null hypothesis : all the pair of means are equal

Ho mean(A) = mean(B)

- Sample are in categorical data.

- Used when the response is continuous data.

Assume:
- data for all sample should be normally distribution.
- variance of all the smaple should be equal.

In [ ]:
dfA = pd.DataFrame({'Col1':np.repeat('A',7),'Col2':np.random.randint(10,30,7)})
dfB = pd.DataFrame({'Col1':np.repeat('B',9),'Col2':np.random.randint(20,40,9)})
dfC = pd.DataFrame({'Col1':np.repeat('C',8),'Col2':np.random.randint(15,30,8)})
df = pd.concat([dfA,dfB,dfC])

ANOVA Model

In [ ]:
# ANOVA Table
mod1 = ols('Col2 ~ Col1',df).fit()
tbl = sm.stats.anova_lm(mod1)
tbl

            df      sum_sq     mean_sq         F    PR(>F)
Col1       2.0  367.619048  183.809524  6.799195  0.005287
Residual  21.0  567.714286   27.034014       NaN       NaN

In [ ]:
# For validating which pair is getting false
print(pairwise_tukeyhsd(df['Col2'],df['Col1']))

 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
     A      B   8.7619 0.0083   2.1573 15.3665   True
     A      C   1.4286 0.8571  -5.3542  8.2113  False
     B      C  -7.3333 0.0222 -13.7015 -0.9652   True
-----------------------------------------------------

## ANOVA CALCULATION

In [ ]:
df = pd.read_excel('data_anova.xlsx')
df.head()

  Col1  Col2
0    A    10
1    A    23
2    A    14
3    A    25
4    A    22

In [ ]:
grp1 = df.groupby('Col1')

sample_mean = grp1.agg('mean')

grand_mean = df['Col2'].mean()

# Calculating "between" value
7*(sample_mean.loc['A'] - grand_mean)**2 + 9*(sample_mean.loc['B'] - grand_mean)**2 + 8*(sample_mean.loc['C'] - grand_mean)**2

sampA = df.Col2[np.where(df.Col1=='A')[0]]
sampB = df.Col2[np.where(df.Col1=='B')[0]]
sampC = df.Col2[np.where(df.Col1=='C')[0]]

sum((np.array(sampA) - np.array(sample_mean.loc['A']))**2) + sum((np.array(sampB) - np.array(sample_mean.loc['B']))**2) + sum((np.array(sampC) - np.array(sample_mean.loc['C']))**2)

np.float64(684.484126984127)

In [ ]:
# ANOVA Table
mod1 = ols('Col2 ~ Col1',df).fit()
tbl = sm.stats.anova_lm(mod1)
tbl

            df      sum_sq     mean_sq          F    PR(>F)
Col1       2.0  842.849206  421.424603  12.929323  0.000219
Residual  21.0  684.484127   32.594482        NaN       NaN

F test statistic : this always ratio of two variance

Formula:

F = variable between sample / variable within sample

Variation within sample : Deviation of each data point from its sample mean

Variable between sample : Deviation of both/all sample with Grand mean

As the value test statistics increase it indicates that we are going away from the expected result. And so the p-value will decrease.

If p-value is small there is the very little possiblity that will happen will be less.

## Interview Question

Q1. Why can't we use 2 sample t test rather than one way ANOVA?

Ans. i) If we have 10 pair then we have to use 10 or 20 times which is time consuming.

ii) when we use 2 sample t test we set 5% LOS, if we are using 20 times then LOS will get multipled which will be dangarous that's why we are using ANOVA

# Multiple ANOVA

Defination:

If the change level of factor has a different impact on the levels of other factor then we say two factors are interacting.

Change of the level Weather from dry to rain has a different impact on Factor car and Bike so we can say weather and mode are interact each other.

---

## Interation Term:

Null Hypothesis : Response are influence by Factor or not
and Vice Versa

In [ ]:
zoo = [34,43,57,40,85,68,67,53,41,24,42,52]
supp=[1,1,1,1,2,2,2,2,3,3,3,3]
lake=["R","D","R","D","R","D","R","D","R","D","R","D"]
df=pd.DataFrame({'Resp':zoo,"Factor1":supp,"Factor2":lake})
df.head()

   Resp  Factor1 Factor2
0    34        1       R
1    43        1       D
2    57        1       R
3    40        1       D
4    85        2       R

In [ ]:
df.nunique()

Resp       12
Factor1     3
Factor2     2
dtype: int64

In [ ]:
model = ols('Resp~Factor1+Factor2',df).fit()
res = sm.stats.anova_lm(model)
res

           df       sum_sq     mean_sq         F    PR(>F)
Factor2   1.0   176.333333  176.333333  0.543765  0.479659
Factor1   1.0    28.125000   28.125000  0.086730  0.775056
Residual  9.0  2918.541667  324.282407       NaN       NaN

In [ ]:
model = ols('Resp~Factor1*Factor2',df).fit()
res = sm.stats.anova_lm(model)
res

                  df       sum_sq     mean_sq         F    PR(>F)
Factor2          1.0   176.333333  176.333333  0.483367  0.506590
Factor1          1.0    28.125000   28.125000  0.077097  0.788312
Factor1:Factor2  1.0     0.125000    0.125000  0.000343  0.985685
Residual         8.0  2918.416667  364.802083       NaN       NaN

## One Sample Varience Test
## Two Sample Varience Test
## Pending

# Revision of all Categorial tests

### 1-sample z test/ 1 sample t test
This test is used to compare the sample mean of one sample sample against a calim value and establish whether their difference is statistically significant or not

### 2-sample t test
This test is used to compare the difference of means of two independent samples against a claim value and establish whether their difference is statistically significant or not

### Paired t test
This test is used when we have two paired samples. The average difference between the paired values is compared against a claim values and establish whether their difference is statistically significant or not
The key word here is before-after

### One way ANOVA
Used when we have multiple samples. This test compares all the pair of the means. It checks whether the difference of each pair of mean can be ignored or not OR can be considered to be equal to 0 or not.
The Ho in this case is that all the pair of means are equal

### Multi way ANOVA
Used when we have multiple factors influencing the response. IN addition to their individual effect, we would also like to study the interactions between various factors.

## Discrete Data Validation

### 1-proportion Test

This test is used to compare proportion calculated from a sample against the claim value and established weather the difference is statistically significant or not.

---

Binomial distribution :

Formula:
mu = mean * p

sd = (n * p * 1-p) **0.5

---

## Normal distribution is used when we have to use approximation in p-value

In [ ]:
'''
40% student coming from MH.
Ho <= 0.4 , Ha > 0.4
in a sample of 400 student are from MH.
'''

print(180/400) # is larger than 0.4

statsmodels.stats.proportion.proportions_ztest(180,400,0.4,alternative='larger')
# We will take action on this bcuz p-value is less than 5%

0.45

(np.float64(2.0100756305184238), np.float64(0.022211592425003045))

## 2-proportion test
This test is used to compare the difference of two proportions calculated from two samples against a claim value and establish whether their difference is statistically significant or not

In [ ]:
'''
Pune CDAC claims that they have atleast 8% more engineer as compared to CDAC

Ho pr(Pune) >= 0.08
Ha pr(Pune) < 0.08

In a sample of 70 students in pune 40 are B.Tech
In a sample of 80 students in Kharghar, 48 are B.Tech
'''

engg = np.array([40,48])
total = np.array([70,80])

statsmodels.stats.proportion.proportions_ztest(engg,total,0.08,alternative='smaller')

(np.float64(-1.3471563869719667), np.float64(0.08896493545619544))

## Chi-square

1. **Chi-square test for goodness of fit:** Used when there are multiple categories. The counts obtained for each category would be compared aginst the claimed pattern to check whether the counts follow the pattern or not. The standard Ho is that the counts follow the pattern

2. **Chi-square test for Degrees of Association:** Used when we wish to check and establish whether one categorical data has an effect on the other categorical data or not.

* Ho: categorical variable A does not influence the choice from categorical variable B

Chi-square test for goodness of fit

In [ ]:
'''
claimed pattern for the qualifications

BTech - 0.4 MTech - 0.1 MCA - 0.3, MSc - 0.2
BTech - 50 Mtech - 20 , MCA - 45, Msc - 25

weather counts obtained from sample follow the pattern or not?
'''
# DO NOT REJECT Situation

count = np.array([50,20,45,25])
pattern = np.array([0.4,0.1,0.3,0.2])

exp_count = sum(count) * pattern
exp_count

scipy.stats.chisquare(count,exp_count)

# But which categories i have to check which is more significant

# Test Statistic
sum((exp_count - count)**2/exp_count)

# Category
(exp_count - count)**2/exp_count

array([0.64285714, 2.57142857, 0.21428571, 0.32142857])

In [ ]:
# REJECT situation
count = np.array([70,10,35,45])
pattern = np.array([0.4,0.1,0.3,0.2])

exp_count = sum(count) * pattern
exp_count

scipy.stats.chisquare(count,exp_count)

# But which categories i have to check which is more significant

# Test Statistic
sum((exp_count - count)**2/exp_count)

# Category wise which had influence on p-value
(exp_count - count)**2/exp_count

array([0.5625    , 2.25      , 3.52083333, 5.28125   ])

Chi-square test for Degrees of Association

In [ ]:
# Gender - Male, Female
# Three Foods - South, Maharashtrian, Gujarati

food = np.array([[45,70,60],[70,40,25]])

scipy.stats.chi2_contingency(food)

# dof => (number of row -1) * (number of column -1)

Chi2ContingencyResult(statistic=np.float64(23.25424258416586), pvalue=np.float64(8.920832446902749e-06), dof=2, expected_freq=array([[64.91935484, 62.09677419, 47.98387097],
       [50.08064516, 47.90322581, 37.01612903]]))